<head>

<script async="" defer="" data-website-id="aedcb0ff-be11-4738-a043-0bc0a04135b2" src="https://umami.okaeri.eu/umami.js"></script>


<meta name="google-site-verification" content="">

<link rel="icon" type="image/png" href="https://cdn.discordapp.com/icons/930168991803142206/11a8c58e2ffddb12f0c133bd3e301eea.webp">
<link rel="apple-touch-icon" type="image/png" href="https://cdn.discordapp.com/icons/930168991803142206/11a8c58e2ffddb12f0c133bd3e301eea.webp">
<link rel="icon" type="image/png" sizes="64x64" href="https://cdn.discordapp.com/icons/930168991803142206/11a8c58e2ffddb12f0c133bd3e301eea.webp">

<link rel="stylesheet" href="/static/fork-awesome/css/fork-awesome.min.css">
<link href="/static/css/bootstrap.min.css" rel="stylesheet">
<link href="/static/css/mdb.min.css" rel="stylesheet">

<title>Sklep SuperCraft.PL</title>

<style>
        .blur {
            -webkit-filter: blur(5px);
            -ms-filter: blur(5px);
            filter: blur(5px);
        }

        .text-black-60 {
            color: rgba(0, 0, 0, 0.6) !important;
        }

        .tab-content {
            padding-top: 1rem;
        }

        .text-tab {
            padding-top: 0.8rem;
        }

        .service-card {
            -webkit-box-shadow: none;
            box-shadow: none;
            border: 1px solid rgba(0, 0, 0, .125);
        }

        .md-tabs {
            margin-left: 0;
            margin-right: 0;
        }

        .w-110 {
            width: 110%;
        }

        /* Sticky footer styles */
        html {
            position: relative;
            min-height: 100%;
        }

        
        body {
            /* Margin bottom by footer height */
            margin-bottom: 53.6px;
        }

        footer {
            position: absolute;
            bottom: 0;
            width: 100%;
            /* Set the fixed height of the footer here */
            height: 53.6px;
        }

        

        .favicon-text {
            font-size: 50px;
            line-height: 1;
            font-weight: 300;
            margin-top: 8px;
            text-transform: uppercase;
            margin-left: 20px;
        }

        .progress-bar[aria-valuenow="0"] {
            color: gray;
        }

        pre {
            white-space: pre-wrap; /* css-3 */
            white-space: -moz-pre-wrap; /* Mozilla, since 1999 */
            white-space: -o-pre-wrap; /* Opera 7 */
            word-wrap: break-word; /* Internet Explorer 5.5+ */
        }
    </style>

<style>
            
body, .grey.lighten-3, button.nav-link {
    background-color: #252525 !important;
}

.list-group > .list-group-item, .dropdown-content {
    background-color: #252525;
}

.list-group > .list-group-item:hover, .dropdown-content li > a, .dropdown-content li > span:hover, .dropdown-content li > a, .dropdown-content li.active {
    background-color: #2c2c2c;
}

.favicon-text, .background-text {
    color: #eeeeee !important;
}

body, .black-text, .btn.btn-link, .toast-close-button:focus, .toast-close-button:hover, table.table a, .pagination .page-item .page-link, .list-group > .list-group-item {
    color: #eeeeee !important;
}

.navbar.navbar-light .navbar-nav .nav-item .nav-link, .white-skin .navbar, .white-skin .navbar .navbar-nav .nav-item a, .white-skin .navbar.double-nav a, button.nav-link {
    color: #eeeeee;
}

.navbar.navbar-light .navbar-nav .nav-item .nav-link:hover, .navbar.navbar-light .navbar-nav .nav-item.active > .nav-link:hover {
    color: #b7b2b2;
}

.list-group-item.active {
    border-color: #000000;
}

.form-control, input.select-dropdown {
   color: #bababa !important;
}

.card, .modal-content, .scrolling-navbar.white, .sidebar-fixed, .white-skin .navbar, .white-skin .side-nav {
    background-color: #2d2d2d !important;
}

.logo-wrapper > .img-fluid {
    filter: invert(1);
}

.breadcrumb {
    background-color: transparent;
}

.primary-color, footer.page-footer.primary-color-dark, ul.stepper li.active a .circle, ul.stepper li.completed a .circle, .blue-gradient, .badge.badge-primary, .gradient-card-header.blue-gradient, .gradient-card-header.indigo, .md-progress .progress-bar {
    background-color: #0152a9 !important;
    background: #ffffff !important;
}

.btn.btn-primary, .btn-primary, .list-group-item.active {
    background-color: #026ada !important;
}

a, a.disabled:hover, a:disabled:hover {
    color: #026ada;
}

.form-check-input[type="checkbox"]:checked + label::before, label.btn input[type="checkbox"]:checked + label::before {
    border-right: 2px solid #026ada;
    border-bottom: 2px solid #026ada;
}

.dropdown-content li > a, .dropdown-content li > span {
    color: #026ada;
}

a:hover {
    color: {{ buttons_hover }};
}
.favicon {
    border-radius: 0.5em !important;
}

.md-tabs .nav-item.open .nav-link, .nav-link.active, .md-tabs, .card, .breadcrumb {
    border-radius: 1em !important;
}

.avatar-img, .btn {
    border-radius: 2em !important;
}


        </style>

<style>
            .favicon-text {
                text-shadow: 0 0 3px #fff;
            }
            body {
                background: url('https://cdn.hipwallpaper.com/i/80/66/13Cb7K.jpg') no-repeat;
                background-size: cover;
                background-attachment: fixed;
            }
        </style>

<style>
        .card-img-top {
            margin-left: auto;
            margin-right: auto;
            width: 190px;
        }
    </style>

<link rel="stylesheet" href="/resources/19IkadaG/custom.css?v=1648038654">
<style type="text/css">/* Chart.js */
@-webkit-keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}@keyframes chartjs-render-animation{from{opacity:0.99}to{opacity:1}}.chartjs-render-monitor{-webkit-animation:chartjs-render-animation 0.001s;animation:chartjs-render-animation 0.001s;}</style><link rel="prefetch" href="https://sklep.rgmc.pl/server/1505"><link rel="prefetch" href="https://sklep.rgmc.pl/page/regulamin-uslug"></head>
